name: Run Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python main.py run

      - name: Upload latest report
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: reports/test_report_*.html
          if-no-files-found: error
